//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

namespace HttpClients {

export class WeatherForecastClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get specific weather forecast.
     * @return OK
     */
    weatherforecastGET(id: string): Promise<WeatherForecast> {
        let url_ = this.baseUrl + "/api/v1/weatherforecast/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json; x-api-version=1.0"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWeatherforecastGET(_response);
        });
    }

    protected processWeatherforecastGET(response: Response): Promise<WeatherForecast> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WeatherForecast.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status === 429) {
            return response.text().then((_responseText) => {
            return throwException("Too Many Requests", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WeatherForecast>(null as any);
    }

    /**
     * Edit weather forecast.
     * @return No Content
     */
    weatherforecastPATCH(id: string, body: WeatherForecastDto): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/weatherforecast/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json; x-api-version=1.0",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWeatherforecastPATCH(_response);
        });
    }

    protected processWeatherforecastPATCH(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status === 429) {
            return response.text().then((_responseText) => {
            return throwException("Too Many Requests", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Delete weather forecast.
     * @return No Content
     */
    weatherforecastDELETE(id: string): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/weatherforecast/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWeatherforecastDELETE(_response);
        });
    }

    protected processWeatherforecastDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 429) {
            return response.text().then((_responseText) => {
            return throwException("Too Many Requests", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Insert weather forecast.
     * @return Created
     */
    weatherforecastPOST(body: WeatherForecastDto): Promise<WeatherForecast> {
        let url_ = this.baseUrl + "/api/v1/weatherforecast";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json; x-api-version=1.0",
                "Accept": "application/json; x-api-version=1.0"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWeatherforecastPOST(_response);
        });
    }

    protected processWeatherforecastPOST(response: Response): Promise<WeatherForecast> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = WeatherForecast.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 429) {
            return response.text().then((_responseText) => {
            return throwException("Too Many Requests", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WeatherForecast>(null as any);
    }
}

/** Represents a weather forecast with details about temperature, date, and summary. */
export class WeatherForecast implements IWeatherForecast {
    /** Primary key */
    id?: string | undefined;
    /** Gets or sets the date of the weather forecast. */
    date?: Date | undefined;
    /** Gets or sets the temperature in degrees Celsius. */
    temperatureC?: number | undefined;
    /** Gets the temperature in degrees Fahrenheit, calculated from the Celsius value. */
    readonly temperatureF?: number | undefined;
    /** Gets or sets a brief description of the weather conditions (e.g., "Sunny", "Rainy"). */
    summary?: string | undefined;

    constructor(data?: IWeatherForecast) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.temperatureC = _data["temperatureC"];
            (<any>this).temperatureF = _data["temperatureF"];
            this.summary = _data["summary"];
        }
    }

    static fromJS(data: any): WeatherForecast {
        data = typeof data === 'object' ? data : {};
        let result = new WeatherForecast();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["temperatureC"] = this.temperatureC;
        data["temperatureF"] = this.temperatureF;
        data["summary"] = this.summary;
        return data;
    }
}

/** Represents a weather forecast with details about temperature, date, and summary. */
export interface IWeatherForecast {
    /** Primary key */
    id?: string | undefined;
    /** Gets or sets the date of the weather forecast. */
    date?: Date | undefined;
    /** Gets or sets the temperature in degrees Celsius. */
    temperatureC?: number | undefined;
    /** Gets the temperature in degrees Fahrenheit, calculated from the Celsius value. */
    temperatureF?: number | undefined;
    /** Gets or sets a brief description of the weather conditions (e.g., "Sunny", "Rainy"). */
    summary?: string | undefined;
}

/** Represents a weather forecast with details about temperature, date, and summary. */
export class WeatherForecastDto implements IWeatherForecastDto {
    /** Primary key */
    id?: string | undefined;
    /** Gets or sets the date of the weather forecast. */
    date?: Date | undefined;
    /** Gets or sets the temperature in degrees Celsius. */
    temperatureC?: number | undefined;
    /** Gets the temperature in degrees Fahrenheit, calculated from the Celsius value. */
    readonly temperatureF?: number | undefined;
    /** Gets or sets a brief description of the weather conditions (e.g., "Sunny", "Rainy"). */
    summary?: string | undefined;

    constructor(data?: IWeatherForecastDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.temperatureC = _data["temperatureC"];
            (<any>this).temperatureF = _data["temperatureF"];
            this.summary = _data["summary"];
        }
    }

    static fromJS(data: any): WeatherForecastDto {
        data = typeof data === 'object' ? data : {};
        let result = new WeatherForecastDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? formatDate(this.date) : <any>undefined;
        data["temperatureC"] = this.temperatureC;
        data["temperatureF"] = this.temperatureF;
        data["summary"] = this.summary;
        return data;
    }
}

/** Represents a weather forecast with details about temperature, date, and summary. */
export interface IWeatherForecastDto {
    /** Primary key */
    id?: string | undefined;
    /** Gets or sets the date of the weather forecast. */
    date?: Date | undefined;
    /** Gets or sets the temperature in degrees Celsius. */
    temperatureC?: number | undefined;
    /** Gets the temperature in degrees Fahrenheit, calculated from the Celsius value. */
    temperatureF?: number | undefined;
    /** Gets or sets a brief description of the weather conditions (e.g., "Sunny", "Rainy"). */
    summary?: string | undefined;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

}